services:
    bdo-chef.kukaw.us:
        build:
            context: ./docker/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '10.10.10.9:${APP_PORT:-80}:80'
            - '10.10.10.9:${VITE_PORT:-5174}:${VITE_PORT:-5174}'
        environment:
            PGID: 1000
            PUID: 1000
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        restart: unless-stopped
networks:
    sail:
        driver: bridge
